services:
  db:
    image: postgres:14
    container_name: my_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - appnet

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    command: bash -c "sleep 10 && poetry run python src/prospectgeo/main.py"
    networks:
      - appnet

networks:
  appnet: