version: '3.8'

services:
  # app:
  #   build: .
  #   container_name: my_python_app
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #     - DATABASE_URL=${DATABASE_URL}  # Use the DATABASE_URL variable from the .env file
  #   depends_on:
  #     - db

  db:
    image: postgres:13
    container_name: my_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"